#!/bin/bash

# (define-fun addone ((x (_ BitVec 8)) (y (_ BitVec 4)) (z (_ BitVec 8))) (_ BitVec 8) (+ (_ bv1 8) x))

FILENAME=correctness.smt

echo "(set-logic BV)" > $FILENAME
echo "; written by the correctness oracle" >> $FILENAME
echo $1 >> $FILENAME

cat << EOM >> $FILENAME

; generated by the correctness oracle

(declare-const i1 (_ BitVec 8))
(declare-const i2 (_ BitVec 8))
; (declare-const i3 (_ BitVec 8))

(define-fun fcorr ((x (_ BitVec 8)) (z (_ BitVec 8))) (_ BitVec 8) (bvsub x z))

(assert
	(not (= 
		(sub i1 i2)
		(fcorr i1 i2)
		))
	)

(check-sat)
(get-model)

EOM

z3 $FILENAME > model.smt
if grep -q unsat model.smt
then
    echo true
else
    echo false
fi
