#!/bin/bash

# (define-fun addone ((x (_ BitVec 8)) (y (_ BitVec 4)) (z (_ BitVec 8))) (_ BitVec 8) (+ (_ bv1 8) x))


# "(define-fun add (( parameter0 (_ BitVec 1))( parameter1 (_ BitVec 1))( parameter2 (_ BitVec 8))( parameter3 (_ BitVec 8))( parameter4 (_ BitVec 8))( parameter5 (_ BitVec 8))) (_ BitVec 8) 
# 	(bvadd (ite (= (_ bv0 1) parameter0) parameter2 parameter3) (ite (= (_ bv0 1) parameter1) parameter4 parameter5)))"

FILENAME=correctness.smt

echo "(set-logic BV)" > $FILENAME
echo "; written by the correctness oracle" >> $FILENAME
echo $1 >> $FILENAME

cat << EOM >> $FILENAME

; generated by the correctness oracle

(declare-const i0 (_ BitVec 8))
(declare-const i1 (_ BitVec 8))
(declare-const i2 (_ BitVec 8))
(declare-const i3 (_ BitVec 8))

(define-fun fcorr ((x (_ BitVec 8)) (z (_ BitVec 8))) (_ BitVec 8) (bvadd x z))

(assert
	(or
		(not (= 
			(add (_ bv0 1) (_ bv1 1) i0 i1 i2 i3)
			(fcorr i0 i3)
			)
		)
		(or
			(not (= 
				(add (_ bv1 1) (_ bv1 1) i0 i1 i2 i3)
				(fcorr i1 i3)
				)
			)
			(not (= 
				(add (_ bv1 1) (_ bv0 1) i0 i1 i2 i3)
				(fcorr i1 i2)
				)
			)
		)

	)
)

(check-sat)
(get-model)

EOM

z3 $FILENAME > model.smt
if grep -q unsat model.smt
then
    echo true
else
    echo false
fi
